name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.12", "3.13"]
        os: ["ubuntu-22.04", "ubuntu-24.04"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup up python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Upgrade setuptools and pip
        if: matrix.os == 'ubuntu-22.04'
        run: pip install --upgrade setuptools pip

      - name: Install dependencies
        run: pip install .

      - name: run tests
        run: python -m unittest discover
